# Site settings
title: 徐進芫's Blog
email: ap_lee@163.com
description: > # this means to ignore newlines until "baseurl:"
  2013.12 - now ERP行业实施人员
  对网络安全感兴趣。
  修习准提法。
  Weibo: @zjuash
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zjuxjy.cc" # the base hostname & protocol for your site
twitter_username: zjuash
github_username:  xjya

# Build settings
markdown: kramdown
